[package]
license = "MIT"
description = "A catsay cli"
name = "catsay-AK"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
assert_cmd = "2.0.16"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
predicates = "3.1.2"
